# Generated by Django 5.1 on 2024-09-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaffeRatings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
