# Generated by Django 5.1 on 2024-09-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaffeRatings', '0003_cafe_unique_cafe_in_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='display',
            field=models.BooleanField(default=False),
        ),
    ]
